### ISSUE TITLE
Corset results missed!!!

### ISSUE THREAD

**Issue by ErisonChen** [Oshlack/Corset#11]
Hi sir ,
we've caught a problems like this.
1.The output log like this ,But we only get **99717** unigenes
![image](https://cloud.githubusercontent.com/assets/11779421/21535375/2f2d65f6-cdaf-11e6-87c2-ae6ada52169c.png)

We tried 3 times and the results are the same.
First .the code is
 `corset -n Z1_24_L3  -g Z1_24_L CORSET/corset.tmp/*.bam`

Second ,the code is

> for FILE in `ls CORSET/corset.tmp/*.bam` ; do
>     corset -r true-stop $FILE &
> done
> wait
> corset -g Z1_24_L -n Z1_24_L3 -i corset *.corset-reads

Third ,the code is exactly like the first time.

Could you help us to figure it out .How could this happen.

**Comment by nadiadavidson** [comment]
Sorry for the slow reply. Only the google group, https://groups.google.com/forum/#!forum/corset-project, is checked regularly for issues. 

Only the first line of your output appears to come from Corset, so I would assume that it has timed out or run out of RAM. The warning you get suggests that there's a problem with the mapping being too loose. Generally Corset will not finish unless the number of transcripts in a pre-cluster is no more than 100 thousand.

I will close this issue for now because it's old , but feel free to repost on the google group for more help.
